### ISSUE TITLE
"View Build" option is broken in Microsoft Teams via Jenkins

### ISSUE THREAD

**Issue by DevOps-IT** [jenkinsci/office-365-connector-plugin#219]
Hi Team,

Could you please help is resolving following issue?

In Jenkins pipeline, we have added Notification Webhook for "Office 365 Connector". When build is notified to Microsoft teams, there is "View Build" button which is having below URL:

http://<JENKINS_URL>/jenkins/job/<JOB_NAME>/job/<JOB>/50/display/redirect which is redirecting to: http://<JENKINS_URL>/jenkins/blue/organizations/jenkins/<JOB_NAME>%2F<JOB>/detail/<JOB>/50/ and throwing 400 error

but actual URL is having "pipeline" in the end.

http://<JENKINS_URL>/jenkins/blue/organizations/jenkins/<JOB_NAME>%2F<JOB>/detail/<JOB>/50/pipeline

How to resolve this? Where to modify this URL? Please help, 

Thanks and Regards,
Vipin Bansal

**Comment by damianszczepanik** [comment]
I don't use Blue ocean and so the plugin may not work with this. If you provide all details so I can reproduce the problem maybe I would be able to help or fix it

**Comment by DevOps-IT** [comment]
Thanks for reply. This issue resolved. I disabled one plugin "Display URL for Blue Ocean" and result is coming fine. I think that plugin is causing some confusion with Teams URL.

Thanks once again. We can close this

**Comment by grayaii** [comment]
Ideally, that link should be customizable, with the default being what it is now.
We're currently getting hit by this too.

**Comment by damianszczepanik** [comment]
Not sure what do you mean

**Comment by malteburkert** [comment]
We experience this issue as well: when clicking 'View Build' the url 'https://teams.microsoft.com/null' is opened instead of the Build detail page within jenkins.

**Comment by Roqche** [comment]
> We experience this issue as well: when clicking 'View Build' the url 'https://teams.microsoft.com/null' is opened instead of the Build detail page within jenkins.

Problem noticed yesterday. Yesterday system status:
```
The connector configuration was old (outlook in URL).
jdk: 8
Windows
```

I thought we should update the JDK version and connector. So the current status:
```
Jenkins: 2.277.4
Plugin: 4.15.0
jdk: OpenJDK 11.0.2
Windows
All other plugins are updated.
The connector URL looks like: https://[name].webhook.office.com/webhookb2/[some GUID]/JenkinsCI/[some GUID]
```

But the problem still exists.

**Comment by Belluk** [comment]
We have a similar issue with the "View Pull Request" Button. It points to "_https://teams.microsoft.com/null_".

Can I set, the url manually or is this a known bug?

Thanks!

**Comment by espguitarist33** [comment]
I have URL's created manually that have the same behavior. Teams on my mobile works, but not desktop. Also, not everybody experienced the issue at once. I'd assume it is a Teams issue

**Comment by Belluk** [comment]
Thanks for your reply, that's interesting. Indeed it also works for my mobile version of Teams...

**Comment by damianszczepanik** [comment]
Have you tried to regenerate hook url? I have done it and some problems have been solved

**Comment by yildiraymeric** [comment]
> We experience this issue as well: when clicking 'View Build' the url 'https://teams.microsoft.com/null' is opened instead of the Build detail page within jenkins.

We have the same problem too. I've regenerate hook url but the same problem still occurs.

**Comment by jvizcarra55** [comment]
> Have you tried to regenerate hook url? I have done it and some problems have been solved

Yes. Multiple times. Issue persists. The webhook seems to be fine since, as others have mentioned, if you click the button on the mobile Teams app it seems to work fine.

**Comment by itruivitorino** [comment]
Just jumping in the conversation. Same problem here (MSTeams Connector)

I also have a HTTP Post Request that uses a custom Payload and had to use markdown with a static URL and a variable since the default option didn't work either (custom Connector)

**Comment by damianszczepanik** [comment]
Then maybe you have regenerated different hook? For regenerated url problems have gone. For old one I see problem on desktop and mobile

**Comment by damianszczepanik** [comment]
OK, I found one more interesting thing: when updating connection configuration (without updating url) desktop Teams is fixed, mobile on team card is fixed but activity card on mobile still displays that message.

**Comment by itruivitorino** [comment]
No URL was changed, I've even tried to make a new one with the same configuration, just to see if there was any mistake made in the past, but no luck. Same result.

I actually don't have any error on the webhook configuration.

**Comment by liaowenming23** [comment]
> We experience this issue as well: when clicking 'View Build' the url 'https://teams.microsoft.com/null' is opened instead of the Build detail page within jenkins.

same problem too, but mobile no problem.

**Comment by damianszczepanik** [comment]
Guys, have you follow this instruction https://docs.microsoft.com/pl-pl/microsoftteams/office-365-custom-connectors ?
This provides guideline that solves problem for me

**Comment by kisa002** [comment]
> > We experience this issue as well: when clicking 'View Build' the url 'https://teams.microsoft.com/null' is opened instead of the Build detail page within jenkins.
> 
> same problem too, but mobile is work.

yeah, same problem too. but mobile is work.
-> https://teams.microsoft.com/null

**Comment by kenjiuno** [comment]
I'm wondering if this problem is caused by connector plugin, or not.

I have tested some URL patterns against section "Jenkins URL" in Jenkins configuration page.

Results:

URL | Reachable
:--|:-:
`http://192.168.2.181:8484/` | No
`http://dd7.local:8484/` | Yes
`http://dd7:8484/` | No

## Pattern 1: `http://192.168.2.181:8484/`

![image](https://user-images.githubusercontent.com/5955540/125878215-864fc7b6-104b-4411-b9d6-b0dd0c583993.png)

build something.

![2021-07-16_10h32_21](https://user-images.githubusercontent.com/5955540/125878225-e4c2dd03-c02d-496a-9bea-7a9f5c2cd95d.png)

`View Build` leads to `https://teams.microsoft.com/null`

![2021-07-16_10h37_57](https://user-images.githubusercontent.com/5955540/125878583-6d752165-8723-45a6-b726-3a02492ff5a5.png)


## Pattern 2: `http://dd7.local:8484/`

![image](https://user-images.githubusercontent.com/5955540/125878299-04eaa412-873b-4b71-ac1e-c90b84263c63.png)

build something.

![2021-07-16_10h33_49](https://user-images.githubusercontent.com/5955540/125878358-733e2274-6d89-4ff0-9b26-ca5bff0590d3.png)

`View Build` leads to `http://dd7.local:8484/job/TeamsTest/2/display/redirect`

![2021-07-16_10h36_23](https://user-images.githubusercontent.com/5955540/125878475-56c6efa2-07f7-4f55-9572-df12ca9c2aeb.png)

## Pattern 3: `http://dd7:8484/`

![image](https://user-images.githubusercontent.com/5955540/125878256-a6bb93f9-e7ed-40ad-a301-b0d09f798190.png)

build something.

![2021-07-16_10h34_39](https://user-images.githubusercontent.com/5955540/125878337-b0380fc2-df8f-4f64-ae1c-0bd7ee848746.png)

`View Build` leads to `https://teams.microsoft.com/null`

![2021-07-16_10h38_22](https://user-images.githubusercontent.com/5955540/125878606-9e25f322-7877-4579-b49e-7b4b3c888303.png)

**Comment by kisa002** [comment]
I think I found a way to solve this problem.
If it's not a secure website (e.g. https), it seems to go to a teams.microsoft.com/null page.
Therefore, I think IP should be set up as an external network and apply SSL.

**Comment by jvizcarra55** [comment]
> I think I found reason for this problem.
> If it's not a secure website (e.g. https), it seems to go to a teams.microsoft.com/null page.
> Therefore, I think IP should be set up as an external network and apply SSL.

I have SSL setup, https://<IP Address>:8443
How do I setup the IP as an external network?
